# Generated by Django 3.1.13 on 2022-05-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measurement",
            fields=[
                ("timestamp", models.DateTimeField(primary_key=True, serialize=False)),
                ("owner_id", models.BigIntegerField()),
                ("repo_id", models.BigIntegerField()),
                ("flag_id", models.BigIntegerField(null=True)),
                ("branch", models.TextField(null=True)),
                ("name", models.TextField()),
                ("value", models.FloatField()),
            ],
        ),
        migrations.RunSQL(
            "ALTER TABLE timeseries_measurement DROP CONSTRAINT timeseries_measurement_pkey;",
            reverse_sql="",
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=[
                    "owner_id",
                    "repo_id",
                    "flag_id",
                    "branch",
                    "name",
                    "timestamp",
                ],
                name="timeseries__owner_i_2cc713_idx",
            ),
        ),
        migrations.RunSQL(
            "SELECT create_hypertable('timeseries_measurement', 'timestamp');",
            reverse_sql="",
        ),
    ]
