# Generated by Django 3.1.13 on 2022-05-23 20:46

from django.db import migrations


class Migration(migrations.Migration):
    # cant create this views in a transaction
    atomic = False

    dependencies = [
        ("timeseries", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
                create materialized view timeseries_measurement_summary_{interval}
                with (timescaledb.continuous) as
                select
                    owner_id,
                    repo_id,
                    branch,
                    name,
                    meta,
                    time_bucket(interval '1 {interval}', timestamp) as timestamp_bin,
                    avg(value) as value_avg,
                    max(value) as value_max,
                    min(value) as value_min,
                    count(value) as value_count
                from timeseries_measurement
                group by
                    owner_id, repo_id, branch, name, meta, timestamp_bin;
            """,
            reverse_sql=f"drop materialized view timeseries_measurement_summary_{interval};",
        )
        for interval in ["hour", "day", "week"]
    ]
