# Generated by Django 3.1.13 on 2022-05-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0002_continuous_aggregates"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSummaryDay",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("owner_id", models.BigIntegerField()),
                ("repo_id", models.BigIntegerField()),
                ("branch", models.TextField()),
                ("name", models.TextField()),
                ("meta", models.TextField()),
                ("value_avg", models.FloatField()),
                ("value_max", models.FloatField()),
                ("value_min", models.FloatField()),
                ("value_count", models.FloatField()),
            ],
            options={
                "db_table": "timeseries_measurement_summary_day",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MeasurementSummaryHour",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("owner_id", models.BigIntegerField()),
                ("repo_id", models.BigIntegerField()),
                ("branch", models.TextField()),
                ("name", models.TextField()),
                ("meta", models.TextField()),
                ("value_avg", models.FloatField()),
                ("value_max", models.FloatField()),
                ("value_min", models.FloatField()),
                ("value_count", models.FloatField()),
            ],
            options={
                "db_table": "timeseries_measurement_summary_hour",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MeasurementSummaryWeek",
            fields=[
                (
                    "timestamp_bin",
                    models.DateTimeField(primary_key=True, serialize=False),
                ),
                ("owner_id", models.BigIntegerField()),
                ("repo_id", models.BigIntegerField()),
                ("branch", models.TextField()),
                ("name", models.TextField()),
                ("meta", models.TextField()),
                ("value_avg", models.FloatField()),
                ("value_max", models.FloatField()),
                ("value_min", models.FloatField()),
                ("value_count", models.FloatField()),
            ],
            options={
                "db_table": "timeseries_measurement_summary_week",
                "managed": False,
            },
        ),
    ]
