# Generated by Django 3.2.12 on 2022-07-27 20:11

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field created_at to dataset
    --
    ALTER TABLE "timeseries_dataset" ADD COLUMN "created_at" timestamp NULL;
    --
    -- Add field updated_at to dataset
    --
    ALTER TABLE "timeseries_dataset" ADD COLUMN "updated_at" timestamp NULL;
    --
    -- Alter field id on dataset
    --
    COMMIT;
    """

    dependencies = [
        ("timeseries", "0006_auto_20220718_1311"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataset",
            name="created_at",
            field=core.models.DateTimeWithoutTZField(null=True),
        ),
        migrations.AddField(
            model_name="dataset",
            name="updated_at",
            field=core.models.DateTimeWithoutTZField(null=True),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
