# Generated by Django 3.2.12 on 2022-08-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0007_auto_20220727_2011"),
    ]

    operations = [
        migrations.RunSQL(
            f"""
            select remove_continuous_aggregate_policy('timeseries_measurement_summary_{name}');
            select add_continuous_aggregate_policy(
                'timeseries_measurement_summary_{name}',
                start_offset => NULL,
                end_offset => NULL,
                schedule_interval => INTERVAL '1 h'
            );
            """,
        )
        for name in ["1day", "7day", "30day"]
    ]
