# Generated by Django 4.1.7 on 2023-04-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0010_auto_20230123_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="measurable_id",
            field=models.TextField(null=True),
        ),
    ]
