# Generated by Django 4.1.7 on 2023-04-27 16:51

from django.db import migrations, models

from utils.migrations import RiskyAddConstraint, RiskyAddIndex


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0010_auto_20230123_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="measurable_id",
            field=models.TextField(null=True),
        ),
        RiskyAddIndex(
            model_name="measurement",
            index=models.Index(
                fields=[
                    "owner_id",
                    "repo_id",
                    "measurable_id",
                    "branch",
                    "name",
                    "timestamp",
                ],
                name="timeseries__owner_i_08d6fe_idx",
            ),
        ),
        RiskyAddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "owner_id",
                    "repo_id",
                    "measurable_id",
                    "commit_sha",
                    "timestamp",
                ),
                name="timeseries_measurement_measurable_unique",
            ),
        ),
    ]
