# Generated by Django 4.1.7 on 2023-04-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0010_auto_20230123_1453'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurement',
            name='timeseries__owner_i_2cc713_idx',
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurable_id',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['owner_id', 'repo_id', 'flag_id', 'measurable_id', 'branch', 'name', 'timestamp'], name='timeseries__owner_i_79f775_idx'),
        ),
    ]
