# Generated by Django 4.1.7 on 2023-05-01 19:29

from django.db import migrations
from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0011_measurement_measurable_id"),
    ]

    operations = [
        RiskyRunSQL(
            "update timeseries_measurement set measurable_id = repo_id::text where name = 'coverage' and measurable_id is null;"
        ),
        RiskyRunSQL(
            "update timeseries_measurement set measurable_id = flag_id::text where name = 'flag_coverage' and measurable_id is null;"
        ),
    ]
