import django.utils.timezone
from django.db import migrations

import core.models
from utils.migrations import (  # Generated by Django 4.1.7 on 2023-05-15 20:46
    RiskyAddIndex,
    RiskyRemoveConstraint,
    RiskyRemoveField,
)


class Migration(migrations.Migration):

    dependencies = [
        ("timeseries", "0013_measurable_indexes_caggs"),
    ]

    operations = [
        RiskyRemoveConstraint(
            model_name="measurement",
            name="timeseries_measurement_flag_unique",
        ),
        RiskyRemoveConstraint(
            model_name="measurement",
            name="timeseries_measurement_noflag_unique",
        ),
        RiskyRemoveField(
            model_name="measurement",
            name="flag_id",
        ),
        migrations.AlterField(
            model_name="dataset",
            name="created_at",
            field=core.models.DateTimeWithoutTZField(
                default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dataset",
            name="updated_at",
            field=core.models.DateTimeWithoutTZField(
                default=django.utils.timezone.now, null=True
            ),
        ),
    ]
