# Generated by Django 3.1.6 on 2021-03-31 17:26

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="Owner",
            fields=[
                ("ownerid", models.AutoField(primary_key=True, serialize=False)),
                ("service", models.CharField(max_length=256)),
                (
                    "username",
                    django.contrib.postgres.fields.citext.CITextField(
                        null=True, unique=True
                    ),
                ),
                ("email", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                ("oauth_token", models.TextField(null=True)),
                ("stripe_customer_id", models.TextField(null=True)),
                ("stripe_subscription_id", models.TextField(null=True)),
                ("createstamp", models.DateTimeField(auto_now_add=True)),
                ("service_id", models.TextField()),
                ("parent_service_id", models.TextField(null=True)),
                ("root_parent_service_id", models.TextField(null=True)),
                ("private_access", models.BooleanField(null=True)),
                ("staff", models.BooleanField(default=False, null=True)),
                ("cache", models.JSONField(null=True)),
                ("plan", models.TextField(default="users-free", null=True)),
                ("plan_provider", models.CharField(max_length=10, null=True)),
                ("plan_user_count", models.SmallIntegerField(default=5, null=True)),
                ("plan_auto_activate", models.BooleanField(default=True, null=True)),
                (
                    "plan_activated_users",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True), null=True, size=None
                    ),
                ),
                ("did_trial", models.BooleanField(null=True)),
                ("free", models.SmallIntegerField(default=0)),
                ("invoice_details", models.TextField(null=True)),
                ("delinquent", models.BooleanField(null=True)),
                ("yaml", models.JSONField(null=True)),
                ("updatestamp", models.DateTimeField(auto_now=True)),
                (
                    "organizations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True), null=True, size=None
                    ),
                ),
                (
                    "admins",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True), null=True, size=None
                    ),
                ),
                ("integration_id", models.IntegerField(null=True)),
                (
                    "permission",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(null=True), null=True, size=None
                    ),
                ),
                ("bot", models.IntegerField(null=True)),
                ("student", models.BooleanField(default=False)),
                ("student_created_at", models.DateTimeField(null=True)),
                ("student_updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "owners",
                "ordering": ["ownerid"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("sessionid", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.TextField(null=True)),
                ("useragent", models.TextField(null=True)),
                ("ip", models.TextField(null=True)),
                ("lastseen", models.DateTimeField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("api", "api"), ("login", "login")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="ownerid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sessions",
                "ordering": ["-lastseen"],
            },
        ),
    ]
