# Generated by Django 2.1.3 on 2019-11-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="plan",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
