# Generated by Django 2.1.3 on 2019-01-16 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='admins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='owner',
            name='permission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
