# Generated by Django 3.1.6 on 2021-04-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="createstamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
