# Generated by Django 2.1.3 on 2020-02-21 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0002_owner_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="plan_activated_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True), null=True, size=None
            ),
        ),
    ]
