# Generated by Django 3.1.13 on 2021-09-30 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0003_auto_20210924_1003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerprofile",
            name="goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("STARTING_WITH_TESTS", "Starting With Tests"),
                        ("IMPROVE_COVERAGE", "Improve Coverage"),
                        ("MAINTAIN_COVERAGE", "Maintain Coverage"),
                        ("TEAM_REQUIREMENTS", "Team Requirements"),
                        ("OTHER", "Other"),
                    ]
                ),
                default=list,
                size=None,
            ),
        ),
    ]
