# Generated by Django 3.1.13 on 2021-10-29 17:09

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("codecov_auth", "0004_auto_20210930_1429"),
    ]

    operations = [
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-basic';")
    ]
