# Generated by Django 2.1.3 on 2020-05-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0004_auto_20200221_1919"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner", name="plan", field=models.TextField(null=True),
        ),
    ]
