# Generated by Django 2.1.3 on 2020-08-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0006_owner_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='useragent',
            field=models.TextField(null=True),
        ),
    ]
