# Generated by Django 3.1.13 on 2022-01-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("codecov_auth", "0007_auto_20211129_1228")]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE owners ALTER COLUMN onboarding_completed SET DEFAULT FALSE;"
        )
    ]
