# Generated by Django 2.1.3 on 2020-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0007_auto_20200811_1631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="lastseen",
            field=models.DateTimeField(null=True),
        ),
    ]
