# Generated by Django 2.1.3 on 2020-08-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0008_auto_20200811_1632"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="type",
            field=models.CharField(
                choices=[("api", "api"), ("login", "login")], max_length=10, null=True
            ),
        ),
    ]
