# Generated by Django 3.1.13 on 2022-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0008_auto_20220119_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="plan",
            field=models.TextField(blank=True, default="users-basic", null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="plan_provider",
            field=models.TextField(
                blank=True,
                choices=[
                    ("github", "Github"),
                    ("gitlab", "Gitlab"),
                    ("bitbucket", "Bitbucket"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="plan_user_count",
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="stripe_customer_id",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="stripe_subscription_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
