# Generated by Django 3.1.13 on 2022-05-11 13:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0008_auto_20220119_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='bot',
            field=models.ForeignKey(blank=True, db_column='bot', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='integration_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='plan',
            field=models.TextField(blank=True, default='users-basic', null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='plan_activated_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='owner',
            name='plan_provider',
            field=models.TextField(blank=True, choices=[('github', 'Github')], null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='plan_user_count',
            field=models.SmallIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='stripe_customer_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='stripe_subscription_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
