# Generated by Django 3.1.13 on 2022-05-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0010_owner_is_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="is_superuser",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
