# Generated by Django 3.2.12 on 2022-05-09 14:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("codecov_auth", "0010_owner_is_superuser"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-enterprisey';"
        ),
        migrations.RunSQL(
            "ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-enterprisem';"
        ),
    ]
