# Generated by Django 2.1.3 on 2020-12-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0010_auto_20200916_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='plan_provider',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
