# Generated by Django 3.2.12 on 2022-06-22 12:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0012_auto_20220531_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="organizations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
