# Generated by Django 3.1.6 on 2021-02-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0013_owner_root_parent_service_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['ownerid']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-lastseen']},
        ),
        migrations.AlterField(
            model_name='owner',
            name='cache',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='yaml',
            field=models.JSONField(null=True),
        ),
    ]
