# Generated by Django 3.2.12 on 2022-08-16 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0014_alter_repositorytoken_token_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="admins",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(null=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
