# Generated by Django 3.2.12 on 2022-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0016_alter_owner_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationleveltoken",
            name="token_type",
            field=models.CharField(
                choices=[("upload", "Upload")], default="upload", max_length=50
            ),
        ),
    ]
