# Generated by Django 3.2.12 on 2022-12-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0018_usertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorytoken",
            name="token_type",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("profiling", "Profiling"),
                    ("static_analysis", "Static Analysis"),
                ],
                max_length=50,
            ),
        ),
    ]
