# Generated by Django 3.2.12 on 2023-01-19 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0019_alter_repositorytoken_token_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="default_org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_org",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
