# Generated by Django 3.2.12 on 2023-02-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0020_ownerprofile_default_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="max_upload_limit",
            field=models.IntegerField(null=True),
        ),
    ]
