# Generated by Django 3.2.12 on 2023-02-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0021_owner_max_upload_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="max_upload_limit",
            field=models.IntegerField(default=150, null=True),
        ),
    ]
