# Generated by Django 3.2.12 on 2023-02-14 11:29

from django.db import migrations

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0022_alter_owner_max_upload_limit"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE owners ALTER COLUMN max_upload_limit SET DEFAULT 150;"
        ),
        RiskyRunSQL(
            "UPDATE owners SET max_upload_limit=150 WHERE max_upload_limit is null;"
        ),
    ]
