# Generated by Django 3.2.12 on 2023-02-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0023_auto_20230214_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="max_upload_limit",
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
    ]
