# Generated by Django 3.2.12 on 2023-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field stripe_coupon_id to owner
    --
    ALTER TABLE "owners" ADD COLUMN "stripe_coupon_id" text NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0024_alter_owner_max_upload_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="stripe_coupon_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
