# Generated by Django 4.1.7 on 2023-03-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0025_owner_stripe_coupon_id"),
    ]

    operations = [
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-sentrym';"),
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-sentryy';"),
    ]
