# Generated by Django 4.1.7 on 2023-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0025_owner_stripe_coupon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="plan_user_count",
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
