# Generated by Django 4.1.7 on 2023-03-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0026_alter_owner_plan_user_count"),
        ("codecov_auth", "0027_owner_sentry_user_data_owner_sentry_user_id"),
    ]

    operations = []
