# Generated by Django 4.1.7 on 2023-03-17 22:01

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0028_owner_sentry_user_data_owner_sentry_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="terms_agreement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="ownerprofile",
            name="terms_agreement_at",
            field=core.models.DateTimeWithoutTZField(null=True),
        ),
    ]
