# Generated by Django 4.1.7 on 2023-05-22 17:53


import django.contrib.postgres.fields.citext
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0030_owner_trial_end_date_owner_trial_start_date"),
    ]

    operations = [
        # NOTE: this migration had to be moved to the `0001_initial` migration
        # since there are internal Django migrations that need to refer to this
        # model via AUTH_USER_MODEL.
        # It is not actually applied there since our `legacy_migrations` override
        # the `migrate` command and mark 0001_initial migrations as fake.  The
        # raw SQL to create this table is in `legacy_migrations` and needs to be applied
        # manually before running this migration.  We have a raw SQL migration below to
        # create the table if it does not already exist.
        #
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('email', django.contrib.postgres.fields.citext.CITextField(null=True)),
        #         ('name', models.TextField(null=True)),
        #         ('is_staff', models.BooleanField(default=False, null=True)),
        #         ('is_superuser', models.BooleanField(default=False, null=True)),
        #         ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
        #     ],
        #     options={
        #         'db_table': 'users',
        #     },
        # ),
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "users" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "external_id" uuid NOT NULL UNIQUE,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "email" citext NULL,
                "name" text NULL,
                "is_staff" boolean NULL,
                "is_superuser" boolean NULL
            );
        """,
            reverse_sql="DROP TABLE users",
        ),
        migrations.AddField(
            model_name="owner",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owners",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
