# Generated by Django 4.1.7 on 2023-07-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0031_user_owner_user"),
    ]

    operations = [
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-trial';"),
        migrations.AddField(
            model_name="owner",
            name="trial_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("ongoing", "Ongoing"),
                    ("expired", "Expired"),
                    ("cannot_trial", "Cannot Trial"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
