# Generated by Django 4.2.2 on 2023-07-06 16:05

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0032_owner_trial_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SentryUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_token", models.TextField(null=True)),
                ("refresh_token", models.TextField(null=True)),
                ("sentry_id", models.TextField(unique=True)),
                ("email", models.TextField(null=True)),
                ("name", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentry_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
