# Generated by Django 4.1.7 on 2023-07-27 23:40

from django.db import migrations, models

from utils.migrations import RiskyAddField


class Migration(migrations.Migration):
    """
        BEGIN;
    --
    -- Add field pretrial_users_count to owner
    --
    ALTER TABLE "owners" ADD COLUMN "pretrial_users_count" smallint NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0034_alter_owner_trial_status"),
    ]

    operations = [
        RiskyAddField(
            model_name="owner",
            name="pretrial_users_count",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
