# Generated by Django 4.2.4 on 2023-08-28 15:23

from collections import Counter
from django.db import migrations

from utils.migrations import RiskyRunPython


def deduplicate_owner_admins_value(apps, schema_editor):
    # Remove duplicate ownerids from owner.admins, fixed a bug where duplicate
    # values would be stored when an admin of a org loads the members page.
    owners = apps.get_model("codecov_auth", "Owner")
    total = 0
    for owner in owners.objects.all():
        if isinstance(owner.admins, list):
            old = owner.admins
            owner.admins = list(set(old))
            owner.save()
            if len(old) != len(owner.admins):
                print(f"Deduplicating for ownerid: {owner.ownerid}")
                print(f"Before: length {len(old)} dict {Counter(old)}")
                print(
                    f"After : length {len(owner.admins)} dict {Counter(owner.admins)}"
                )
                total += len(old) - len(owner.admins)
    print(f"Total duplicate ownerids removed: {total}")


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0035_owner_pretrial_users_count"),
    ]

    operations = [
        RiskyRunPython(deduplicate_owner_admins_value),
    ]
