# Generated by Django 4.2.2 on 2023-08-17 20:59

from django.db import migrations, models

from utils.migrations import RiskyAddField


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0035_owner_pretrial_users_count"),
    ]

    operations = [
        RiskyAddField(
            model_name="owner",
            name="uses_invoice",
            field=models.BooleanField(null=True),
        ),
    ]
