# Generated by Django 4.2.2 on 2023-08-30 13:27

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field terms_agreement to user
    --
    ALTER TABLE "users" ADD COLUMN "terms_agreement" boolean NULL;
    --
    -- Add field terms_agreement_at to user
    --
    ALTER TABLE "users" ADD COLUMN "terms_agreement_at" timestamp NULL;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0035_owner_pretrial_users_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_agreement",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_agreement_at",
            field=core.models.DateTimeWithoutTZField(null=True),
        ),
    ]
