# Generated by Django 4.2.2 on 2023-08-28 17:42

from django.db import migrations, models

from utils.migrations import RiskyAlterField


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0036_owner_uses_invoice"),
    ]

    operations = [
        RiskyAlterField(
            model_name="owner",
            name="uses_invoice",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
