# Generated by Django 4.2.2 on 2023-08-17 20:59

from django.db import migrations, models
from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0036_add_user_terms_agreement"),
    ]

    operations = [
        RiskyAddField(
            model_name="owner",
            name="uses_invoice",
            field=models.BooleanField(null=True),
        ),
    ]
