# Generated by Django 4.2.2 on 2023-08-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0036_add_user_terms_agreement"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE users
            SET
                terms_agreement = subquery.terms_agreement,
                terms_agreement_at = subquery.terms_agreement_at
            FROM (
                SELECT
                    owners.user_id,
                    codecov_auth_ownerprofile.terms_agreement,
                    codecov_auth_ownerprofile.terms_agreement_at
                FROM owners
                INNER JOIN codecov_auth_ownerprofile
                ON codecov_auth_ownerprofile.owner_id = owners.ownerid
            ) subquery
            WHERE subquery.user_id = users.id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
