# Generated by Django 4.2.2 on 2023-09-14 23:55

from django.db import migrations


class Migration(migrations.Migration):
    # BEGIN;
    # --
    # -- Raw SQL operation
    # --
    # ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litem';
    # COMMIT;

    dependencies = [
        ("codecov_auth", "0039_alter_owner_uses_invoice"),
    ]

    operations = [
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litem';"),
    ]
