# Generated by Django 4.2.2 on 2023-09-18 18:25

from django.db import migrations


class Migration(migrations.Migration):
    # BEGIN;
    # --
    # -- Raw SQL operation
    # --
    # ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litem';
    # --
    # -- Raw SQL operation
    # --
    # ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litey';
    # COMMIT;

    dependencies = [
        ("codecov_auth", "0040_oktauser"),
    ]

    operations = [
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litem';"),
        migrations.RunSQL("ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-litey';"),
    ]
