# Generated by Django 4.2.3 on 2023-09-19 20:58

from django.db import migrations

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0041_remove_owner_agreements_and_alter_user_agreements"),
    ]

    operations = [
        RiskyRunSQL(
            sql="""
            ALTER TABLE codecov_auth_ownerprofile
            DROP COLUMN terms_agreement,
            DROP COLUMN terms_agreement_at;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
