# Generated by Django 4.2.3 on 2023-09-19 20:52

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0043_sync_user_terms_agreement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownerprofile",
            name="terms_agreement",
        ),
        migrations.RemoveField(
            model_name="ownerprofile",
            name="terms_agreement_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="terms_agreement",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="terms_agreement_at",
            field=core.models.DateTimeWithoutTZField(blank=True, null=True),
        ),
    ]
