# Generated by Django 4.2.3 on 2023-09-21 14:24

from django.db import migrations

from utils.migrations import RiskyRemoveField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Remove field terms_agreement from ownerprofile
    --
    ALTER TABLE "codecov_auth_ownerprofile" DROP COLUMN "terms_agreement" CASCADE;
    --
    -- Remove field terms_agreement_at from ownerprofile
    --
    ALTER TABLE "codecov_auth_ownerprofile" DROP COLUMN "terms_agreement_at" CASCADE;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0044_remove_owner_agreements_and_alter_user_agreements"),
    ]

    operations = [
        RiskyRemoveField(
            model_name="ownerprofile",
            name="terms_agreement",
        ),
        RiskyRemoveField(
            model_name="ownerprofile",
            name="terms_agreement_at",
        ),
    ]
