# Generated by Django 4.2.3 on 2023-09-19 19:48


from django.db import migrations

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("codecov_auth", "0045_remove_ownerprofile_terms_agreement"),
    ]

    operations = [
        RiskyRunSQL(
            sql="""
            UPDATE owners
            SET admins = ARRAY (
                SELECT v
                FROM   unnest(admins) WITH ORDINALITY t(v,ord)
                GROUP  BY 1
                ORDER  BY min(ord)
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
