# Generated by Django 4.2.3 on 2023-10-09 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0046_dedupe_owner_admin_values"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-teamm';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TYPE plans ADD VALUE IF NOT EXISTS 'users-teamy';",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
