# Generated by Django 4.2.7 on 2024-02-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0048_githubappinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='customer_intent',
            field=models.TextField(choices=[('BUSINESS', 'Business'), ('PERSONAL', 'Personal')], null=True),
        ),
    ]
