# Generated by Django 4.2.7 on 2024-02-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
        BEGIN;
        --
        -- Alter field tier on ownertierpermission
        --
        SET CONSTRAINTS "codecov_auth_ownerti_tier_id_d682acb8_fk_codecov_a" IMMEDIATE; ALTER TABLE "codecov_auth_ownertierpermission" DROP CONSTRAINT "codecov_auth_ownerti_tier_id_d682acb8_fk_codecov_a";
        ALTER TABLE "codecov_auth_ownertierpermission" ADD CONSTRAINT "codecov_auth_ownerti_tier_id_d682acb8_fk_codecov_a" FOREIGN KEY ("tier_id") REFERENCES "codecov_auth_ownertier" ("id") DEFERRABLE INITIALLY DEFERRED;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0049_ownerpermission_ownertier_ownertierplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownertierpermission",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier",
                to="codecov_auth.ownertier",
            ),
        ),
    ]
