# Generated by Django 4.2.7 on 2024-02-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codecov_auth', '0049_ownerprofile_customer_intent'),
    ]

    # BEGIN;
    # --
    # -- Remove field customer_intent from ownerprofile
    # --
    # ALTER TABLE "codecov_auth_ownerprofile" DROP COLUMN "customer_intent" CASCADE;
    # COMMIT;
    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='customer_intent',
        ),
    ]
