# Generated by Django 4.2.7 on 2024-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0050_remove_ownerprofile_customer_intent"),
    ]

    # BEGIN;
    # --
    # -- Remove field customer_intent from ownerprofile
    # --
    # ALTER TABLE "codecov_auth_ownerprofile" DROP COLUMN "customer_intent" CASCADE;
    # COMMIT;
    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_intent",
            field=models.TextField(
                choices=[("BUSINESS", "Business"), ("PERSONAL", "Personal")], null=True
            ),
        ),
    ]
