# Generated by Django 4.2.7 on 2024-02-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0050_remove_ownerprofile_customer_intent"),
    ]

    # BEGIN;
    # --
    # -- Add field customer_intent to user
    # --
    # ALTER TABLE "users" ADD COLUMN "customer_intent" text NULL;
    # COMMIT;
    operations = [
        migrations.AddField(
            model_name="user",
            name="customer_intent",
            field=models.TextField(
                choices=[("BUSINESS", "Business"), ("PERSONAL", "Personal")], null=True
            ),
        ),
    ]
