# Generated by Django 4.2.7 on 2024-02-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Alter field tier on ownertierplan
    --
    SET CONSTRAINTS "codecov_auth_ownerti_tier_id_46ba5222_fk_codecov_a" IMMEDIATE; ALTER TABLE "codecov_auth_ownertierplan" DROP CONSTRAINT "codecov_auth_ownerti_tier_id_46ba5222_fk_codecov_a";
    ALTER TABLE "codecov_auth_ownertierplan" ADD CONSTRAINT "codecov_auth_ownerti_tier_id_46ba5222_fk_codecov_a" FOREIGN KEY ("tier_id") REFERENCES "codecov_auth_ownertier" ("id") DEFERRABLE INITIALLY DEFERRED;
    COMMIT;
    """

    dependencies = [
        ("codecov_auth", "0050_alter_ownertierpermission_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownertierplan",
            name="tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tier_plan",
                to="codecov_auth.ownertier",
            ),
        ),
    ]
