# Generated by Django 4.2.7 on 2024-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    # BEGIN;
    # --
    # -- Add field app_id to githubappinstallation
    # --
    # ALTER TABLE "codecov_auth_githubappinstallation" ADD COLUMN "app_id" integer NULL;
    # --
    # -- Add field pem_path to githubappinstallation
    # --
    # ALTER TABLE "codecov_auth_githubappinstallation" ADD COLUMN "pem_path" text NULL;
    # COMMIT;

    dependencies = [
        ("codecov_auth", "0051_user_customer_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubappinstallation",
            name="app_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="githubappinstallation",
            name="pem_path",
            field=models.TextField(null=True),
        ),
    ]
