# Generated by Django 4.2.7 on 2024-02-21 16:03

import uuid

import django.db.models.deletion
import django_prometheus.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codecov_auth", "0052_githubappinstallation_app_id_and_more"),
    ]

    # BEGIN;
    #     --
    #     -- Create model OwnerInstallationNameToUseForTask
    #     --
    #     CREATE TABLE "codecov_auth_ownerinstallationnametousefortask" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "external_id" uuid NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "installation_name" text NOT NULL, "task_name" text NOT NULL, "owner_id" integer NOT NULL);
    #     --
    #     -- Create constraint single_task_name_per_owner on model ownerinstallationnametousefortask
    #     --
    #     CREATE UNIQUE INDEX "single_task_name_per_owner" ON "codecov_auth_ownerinstallationnametousefortask" ("owner_id", "task_name");
    #     ALTER TABLE "codecov_auth_ownerinstallationnametousefortask" ADD CONSTRAINT "codecov_auth_ownerin_owner_id_8bf0ce9b_fk_owners_ow" FOREIGN KEY ("owner_id") REFERENCES "owners" ("ownerid") DEFERRABLE INITIALLY DEFERRED;
    #     CREATE INDEX "codecov_auth_ownerinstalla_owner_id_8bf0ce9b" ON "codecov_auth_ownerinstallationnametousefortask" ("owner_id");
    # COMMIT;

    operations = [
        migrations.CreateModel(
            name="OwnerInstallationNameToUseForTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installation_name", models.TextField()),
                ("task_name", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installation_name_to_use_for_tasks",
                        to="codecov_auth.owner",
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin(
                    "codecov_auth.github_app_installation"
                ),
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="ownerinstallationnametousefortask",
            constraint=models.UniqueConstraint(
                models.F("owner_id"),
                models.F("task_name"),
                name="single_task_name_per_owner",
            ),
        ),
    ]
