# Generated by Django 3.1.13 on 2021-11-01 14:48

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_customer_id", models.TextField(null=True)),
                ("stripe_subscription_id", models.TextField(null=True)),
                ("plan", models.TextField(default="users-free", null=True)),
                (
                    "plan_provider",
                    models.TextField(choices=[("github", "Github")], null=True),
                ),
                ("plan_user_count", models.SmallIntegerField(default=5, null=True)),
                ("plan_auto_activate", models.BooleanField(default=True, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
