# Generated by Django 3.1.13 on 2021-11-03 18:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_customer_id", models.TextField(null=True)),
                ("stripe_subscription_id", models.TextField(null=True)),
                ("plan", models.TextField(default="users-free")),
                (
                    "plan_provider",
                    models.TextField(choices=[("github", "Github")], null=True),
                ),
                ("max_activated_user_count", models.SmallIntegerField(default=5)),
                ("should_auto_activate_users", models.BooleanField(default=True)),
            ],
            options={"abstract": False,},
        ),
    ]
