# Generated by Django 3.1.13 on 2022-01-18 12:32

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TYPE notifications ADD VALUE IF NOT exists 'checks_patch';"
        ),
        migrations.RunSQL(
            "ALTER TYPE notifications ADD VALUE IF NOT exists 'checks_project';"
        ),
        migrations.RunSQL(
            "ALTER TYPE notifications ADD VALUE IF NOT exists 'checks_changes';"
        ),
    ]
