# Generated by Django 4.2.11 on 2024-07-24 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_auto_20220118_1232"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
