ignore:
  - "**tests**/test_*.py"
comment:
  show_critical_paths: true

beta_groups:
  - "labels"

flag_management:
  individual_flags:
    - name: "smart-labels"
      carryforward: true
      carryforward_mode: "labels"

codecov:
  require_ci_to_pass: false

test_analytics:
  flake_detection: true
