FROM python:3.7-alpine

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc \ 
 musl-dev \ 
 postgresql-dev \ 
 python3-dev

RUN mkdir -p /app

COPY requirements.txt ./app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY manage.py ./app/manage.py
EXPOSE 8000

