setup:
  codecov_url: https://codecov.io
  debug: no
  loglvl: INFO
  encryption_secret: "zp^P9*i8aR3"
  media:
    assets: https://codecov-cdn.storage.googleapis.com/4.4.4-fd6aa1e
    dependancies: https://codecov-cdn.storage.googleapis.com/4.4.4-fd6aa1e
  http:
    force_https: yes
    cookie_secret: Z1353^dggqdbc,kp0)661
    timeouts:
      connect: 10
      receive: 15
  tasks:
    celery:
      soft_timelimit: 200
      hard_timelimit: 240
    upload:
      queue: uploads
  cache:
    yaml: 600  # 10 minutes
    tree: 600  # 10 minutes
    diff: 300  # 5 minutes
    chunks: 300  # 5 minutes
    uploads: 86400  # 1 day

services:
  redis_url: redis://redis:@localhost:6379/
  database:
    username: postgres
    name: postgres
    password: postgres
    host: localhost
  minio:
    hash_key: testixik8qdauiab1yiffydimvi72ekq  # never change this
    periodic_callback_ms: false
    access_key_id: codecov-default-key
    secret_access_key: codecov-default-secret
    verify_ssl: false
  sentry:
    server_dsn: https://e15a77ae50f9454c8255dee12e764186@sentry.io/1260170
  google_analytics_key: UA-63027104-1
  circleci_token: testquyiqktx1o6in8zutfdwikzwe0kgclxy9j27
