# Generated by Django 2.1.3 on 2019-05-20 20:50

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codecov_auth', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.TextField(db_column='branch', primary_key=True, serialize=False)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, db_column='authors', null=True, size=None)),
                ('updatestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commitid', models.TextField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updatestamp', models.DateTimeField(auto_now=True)),
                ('ci_passed', models.BooleanField()),
                ('totals', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report', django.contrib.postgres.fields.jsonb.JSONField()),
                ('merged', models.NullBooleanField()),
                ('deleted', models.NullBooleanField()),
                ('notified', models.NullBooleanField()),
                ('branch', models.TextField()),
                ('pullid', models.IntegerField()),
                ('message', models.TextField()),
                ('parent_commit_id', models.TextField(db_column='parent')),
                ('state', models.CharField(max_length=256)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commits',
            },
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('pullid', models.IntegerField(primary_key=True, serialize=False)),
                ('issueid', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('commentid', models.CharField(max_length=100)),
                ('updatestamp', models.DateTimeField(auto_now=True)),
                ('diff', django.contrib.postgres.fields.jsonb.JSONField()),
                ('flare', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base', models.ForeignKey(db_column='base', on_delete=django.db.models.deletion.CASCADE, related_name='pull_base', to='core.Commit')),
                ('compared_to', models.ForeignKey(db_column='compared_to', on_delete=django.db.models.deletion.CASCADE, related_name='compared_to', to='core.Commit')),
                ('head', models.ForeignKey(db_column='head', on_delete=django.db.models.deletion.CASCADE, related_name='pull_head', to='core.Commit')),
            ],
            options={
                'db_table': 'pulls',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repoid', models.AutoField(primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.citext.CITextField()),
                ('service_id', models.TextField()),
                ('private', models.BooleanField()),
                ('updatestamp', models.DateTimeField(auto_now=True)),
                ('active', models.NullBooleanField()),
                ('author', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'repos',
            },
        ),
        migrations.AddField(
            model_name='pull',
            name='repository',
            field=models.ForeignKey(db_column='repoid', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='core.Repository'),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(db_column='repoid', on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='core.Repository'),
        ),
        migrations.AddField(
            model_name='branch',
            name='head',
            field=models.ForeignKey(db_column='head', on_delete=django.db.models.deletion.CASCADE, related_name='branch_head', to='core.Commit'),
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(db_column='repoid', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.Repository'),
        ),
    ]
