# Generated by Django 3.1.6 on 2021-05-17 12:23

from django.db import migrations, models

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="active",
            field=models.BooleanField(default=False, null=True),
        ),
        RiskyRunSQL("UPDATE repos SET active=false WHERE active is null;"),
    ]
