# Generated by Django 2.1.3 on 2019-02-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='service',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
