# Generated by Django 2.1.3 on 2019-07-25 21:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='branch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='fork',
            field=models.ForeignKey(blank=True, db_column='forkid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Repository'),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='upload_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='version',
            name='version',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
