# Generated by Django 3.1.6 on 2021-05-20 08:41

from django.db import migrations, models

from utils.migrations import RiskyRunSQL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210517_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="language",
            field=models.TextField(
                blank=True,
                choices=[
                    ("javascript", "Javascript"),
                    ("shell", "Shell"),
                    ("python", "Python"),
                    ("ruby", "Ruby"),
                    ("perl", "Perl"),
                    ("dart", "Dart"),
                    ("java", "Java"),
                    ("c", "C"),
                    ("clojure", "Clojure"),
                    ("d", "D"),
                    ("fortran", "Fortran"),
                    ("go", "Go"),
                    ("groovy", "Groovy"),
                    ("kotlin", "Kotlin"),
                    ("php", "Php"),
                    ("r", "R"),
                    ("scala", "Scala"),
                    ("swift", "Swift"),
                    ("objective-c", "Objective C"),
                    ("xtend", "Xtend"),
                ],
                null=True,
            ),
        ),
        RiskyRunSQL("ALTER TABLE repos ALTER COLUMN active SET DEFAULT FALSE;"),
        RiskyRunSQL("UPDATE repos SET active=false WHERE active is null;"),
    ]
