# Generated by Django 3.1.6 on 2021-06-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210520_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="pull",
            name="user_provided_base_sha",
            field=models.TextField(null=True),
        ),
    ]
