# Generated by Django 2.1.3 on 2019-09-30 23:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20190725_2147"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="cache",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="yaml",
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
