# Generated by Django 3.1.13 on 2021-09-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_pull_user_provided_base_sha"),
    ]

    operations = [
        migrations.AddField(
            model_name="pull",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pull", name="pullid", field=models.IntegerField(),
        ),
    ]
