# Generated by Django 2.1.3 on 2019-11-11 22:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20190930_2341"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="image_token",
            field=models.CharField(default=core.models._gen_image_token, max_length=10),
        ),
    ]
