# Generated by Django 2.1.3 on 2019-12-12 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_repository_image_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='bot',
            field=models.ForeignKey(db_column='bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_repos', to=settings.AUTH_USER_MODEL),
        ),
    ]
