# Generated by Django 2.1.3 on 2020-02-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200106_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
