# Generated by Django 2.1.3 on 2020-02-18 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200213_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='base',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='ci_passed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='parent_commit_id',
            field=models.TextField(db_column='parent', null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='pullid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='report',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='totals',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='commentid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='diff',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='flare',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='issueid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='state',
            field=models.CharField(default='open', max_length=100),
        ),
        migrations.AlterField(
            model_name='pull',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='activated',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repository',
            name='branch',
            field=models.TextField(default='master', null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='hookid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='using_integration',
            field=models.NullBooleanField(),
        ),
    ]
