# Generated by Django 2.1.3 on 2020-02-20 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reconcile_fields_with_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='author',
            field=models.ForeignKey(db_column='author', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
