# Generated by Django 3.2.12 on 2022-05-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_decoration_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="repository",
            name="repos_service_ids",
        ),
        migrations.AddConstraint(
            model_name="repository",
            constraint=models.UniqueConstraint(
                fields=("service_id", "author"), name="repos_service_ids"
            ),
        ),
    ]
