# Generated by Django 2.1.3 on 2020-03-10 16:00

import core.encoders
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20200220_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="author",
            field=models.ForeignKey(
                db_column="author",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commit",
            name="report",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=core.encoders.ReportJSONEncoder, null=True
            ),
        ),
    ]
