# Generated by Django 2.1.3 on 2020-08-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200310_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='updatestamp',
            field=models.DateTimeField(),
        ),
    ]
