# Generated by Django 3.2.12 on 2022-05-03 02:57

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("core", "0012_auto_20220511_1732"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="repository",
            index=models.Index(
                fields=["service_id", "author"], name="repos_service_id_author"
            ),
        ),
    ]
