# Generated by Django 3.2.12 on 2022-07-11 13:34

from django.db import migrations, models

from utils.migrations import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index pulls_author_updatestamp on field(s) author, updatestamp of model pull
    --
    CREATE INDEX "pulls_author_updatestamp" ON "pulls" ("author", "updatestamp");
    COMMIT;
    """

    dependencies = [
        ("core", "0013_repository_repos_service_id_author"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="pull",
            index=models.Index(
                fields=["author", "updatestamp"], name="pulls_author_updatestamp"
            ),
        ),
    ]
