# Generated by Django 2.1.3 on 2020-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200807_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='updatestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
