# Generated by Django 3.2.12 on 2022-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_repository_repos_service_id_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitYamlError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_code', models.CharField(max_length=100)),
                ('error_params', models.JSONField(default=dict)),
                ('commit', models.ForeignKey(db_column='commitid', on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.commit')),
            ],
            options={
                'db_table': 'commit_yamlerror',
            },
        ),
    ]
