# Generated by Django 3.2.12 on 2022-08-09 10:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_repository_repos_service_id_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="PossibleError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(null=True, unique=True)),
                (
                    "type",
                    models.TextField(
                        choices=[("yaml", "Yaml"), ("bot", "Bot")], null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommitError",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_params", models.JSONField(default=dict)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="core.commit",
                    ),
                ),
                (
                    "error_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_types",
                        to="core.possibleerror",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
