# Generated by Django 3.2.12 on 2022-08-09 15:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_pull_pulls_author_updatestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitError",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(max_length=100)),
                ("error_params", models.JSONField(default=dict)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="core.commit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
