# Generated by Django 3.2.12 on 2023-01-13 16:44

from django.db import migrations, models

from utils.migrations import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index branches_repoid_updatestamp on field(s) repository, -updatestamp of model branch
    --
    CREATE INDEX "branches_repoid_updatestamp" ON "branches" ("repoid", "updatestamp" DESC);
    COMMIT;
    """

    dependencies = [
        ("core", "0016_version_v4_6_6"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="branch",
            index=models.Index(
                fields=["repository", "-updatestamp"],
                name="branches_repoid_updatestamp",
            ),
        ),
    ]
