# Generated by Django 3.2.12 on 2023-02-01 15:04

from django.db import migrations, models

from utils.migrations import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index commits_repoid_branch_state_ts on field(s) repository, branch, state, -timestamp of model commit
    --
    CREATE INDEX "commits_repoid_branch_state_ts" ON "commits" ("repoid", "branch", "state", "timestamp" DESC);
    COMMIT;
    """

    dependencies = [
        ("core", "0018_commit_all_commits_on_pull"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="commit",
            index=models.Index(
                fields=["repository", "branch", "state", "-timestamp"],
                name="commits_repoid_branch_state_ts",
            ),
        ),
    ]
