# Generated by Django 4.1.7 on 2023-04-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_commit_commits_repoid_commitid_short_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pull",
            name="behind_by",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="pull",
            name="behind_by_commit",
            field=models.TextField(null=True),
        ),
    ]
