# Generated by Django 4.1.7 on 2023-04-10 15:50

from django.db import migrations, models

from utils.migrations import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Create index pulls_repository_updatestamp on field(s) repository, updatestamp of model pull
    --
    CREATE INDEX "pulls_repository_updatestamp" ON "pulls" ("repoid", "updatestamp");
    COMMIT;
    """

    dependencies = [
        ("core", "0021_pull_behind_by_pull_behind_by_commit"),
    ]

    operations = [
        RiskyAddIndex(
            model_name="pull",
            index=models.Index(
                fields=["repository", "updatestamp"],
                name="pulls_repository_updatestamp",
            ),
        ),
    ]
