# Generated by Django 4.1.7 on 2023-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    #     --
    # -- Alter field decoration_type on commitnotification
    # --
    # -- (no-op)
    # --
    # -- Raw SQL operation
    # --
    # ALTER TYPE decorations ADD VALUE IF NOT exists 'passing_empty_upload';
    # --
    # -- Raw SQL operation
    # --
    # ALTER TYPE decorations ADD VALUE IF NOT exists 'failing_empty_upload';

    atomic = False
    dependencies = [
        ("core", "0022_pull_pulls_repoid_pullid_ts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commitnotification",
            name="decoration_type",
            field=models.TextField(
                choices=[
                    ("standard", "Standard"),
                    ("upgrade", "Upgrade"),
                    ("upload_limit", "Upload Limit"),
                    ("passing_empty_upload", "Passing Empty Upload"),
                    ("failing_empty_upload", "Failing Empty Upload"),
                ],
                null=True,
            ),
        ),
        migrations.RunSQL(
            "ALTER TYPE decorations ADD VALUE IF NOT exists 'passing_empty_upload';"
        ),
        migrations.RunSQL(
            "ALTER TYPE decorations ADD VALUE IF NOT exists 'failing_empty_upload';"
        ),
    ]
