# Generated by Django 4.1.7 on 2023-06-05 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_v5_0_1"),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TYPE notifications ADD VALUE IF NOT exists 'codecov_slack_app';            
            """
        ),
    ]
