# Generated by Django 4.2.2 on 2023-07-18 07:33

from django.db import migrations, models

import core.encoders


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_auto_20230605_1134"),
    ]

    # BEGIN;
    # --
    # -- Alter field report on commit
    # --
    # -- (no-op)
    # --
    # -- Rename field report on commit to _report
    # --
    # -- (no-op)
    # --
    # -- Add field _report_storage_path to commit
    # --
    # ALTER TABLE "commits" ADD COLUMN "report_storage_path" varchar(200) NULL;
    # COMMIT;

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="report",
            field=models.JSONField(
                db_column="report", encoder=core.encoders.ReportJSONEncoder, null=True
            ),
        ),
        migrations.RenameField(
            model_name="commit",
            old_name="report",
            new_name="_report",
        ),
        migrations.AddField(
            model_name="commit",
            name="_report_storage_path",
            field=models.URLField(db_column="report_storage_path", null=True),
        ),
    ]
