# Generated by Django 4.2.2 on 2023-07-24 17:19

import datetime
import uuid

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_commit_report_rename_report_commit__report_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Install",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("install_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "date_created",
                    core.models.DateTimeWithoutTZField(default=datetime.datetime.now),
                ),
            ],
        ),
    ]
