# Generated by Django 4.2.2 on 2023-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_repository_webhook_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constants",
            fields=[
                ("key", models.CharField(primary_key=True, serialize=False)),
                ("value", models.CharField()),
            ],
            options={
                "db_table": "constants",
            },
        ),
    ]
