# Generated by Django 4.2.2 on 2023-07-24 17:19

from django.db import migrations


def generate_install_id(apps, schema_editor):
    Install = apps.get_model("core", "Install")
    new_install = Install()
    new_install.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_install"),
    ]

    operations = [
        migrations.RunPython(generate_install_id),
    ]
