# Generated by Django 4.2.2 on 2023-07-27 15:39

from uuid import uuid4

from django.db import migrations


def generate_constants(apps, schema_editor):
    Constants = apps.get_model("core", "Constants")
    version = Constants(key="version", value="23.7.27")
    install_id = Constants(key="install_id", value=uuid4())
    version.save()
    install_id.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_constants_delete_version"),
    ]

    operations = [migrations.RunPython(generate_constants)]
