# Generated by Django 4.2.2 on 2023-07-31 16:27

from django.db import migrations


def update_version(apps, schema_editor):
    version = apps.get_model("core", "Version")
    version.objects.all().delete()
    v = version(version="23.7.27")
    v.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_auto_20230727_1539"),
    ]

    operations = [migrations.RunPython(update_version)]
