# Generated by Django 4.2.2 on 2023-07-31 16:41

from django.db import migrations
from shared.django_apps.migration_utils import RiskyRunSQL


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_auto_20230731_1627"),
    ]

    operations = [
        RiskyRunSQL(
            """
            create or replace function branches_update() returns trigger as $$
            declare _ownerid int;
            begin
                -- update repos cache if main branch
                update repos
                set updatestamp = now()
                where repoid = new.repoid
                    and branch = new.branch
                returning ownerid into _ownerid;

                if found then
                -- default branch updated, so we can update the owners timestamp
                -- to refresh the team list
                update owners
                set updatestamp=now()
                where ownerid=_ownerid;
                end if;

                return null;
            end;
            $$ language plpgsql;
        """
        )
    ]
