# Generated by Django 4.2.2 on 2023-08-14 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0033_alter_pull_flare_rename_flare_pull__flare_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            state_operations=[
                migrations.RemoveField(
                    model_name="repository",
                    name="cache",
                )
            ],
        )
    ]
