# Generated by Django 4.2.2 on 2023-07-27 15:39

from uuid import uuid4

from django.db import migrations


def generate_constants(apps, schema_editor):
    Constants = apps.get_model("core", "Constants")
    version = Constants(key="version", value="23.9.5")
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_remove_repository_cache"),
    ]

    operations = [migrations.RunPython(generate_constants)]
