# Generated by Django 4.2.2 on 2023-09-07 21:23

from django.db import migrations


class Migration(migrations.Migration):
    def add_version(apps, schema):
        Constants = apps.get_model("core", "Constants")
        version = Constants.objects.get(key="version")
        version.value = "23.9.5"
        version.save()

    dependencies = [
        ("core", "0034_remove_repository_cache"),
    ]

    operations = [migrations.RunPython(add_version)]
