# Generated by Django 4.2.3 on 2023-10-03 13:42

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "23.10.2"
    version.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_auto_20230907_2123"),
    ]

    operations = [migrations.RunPython(update_version)]
