# Generated by Django 4.2.3 on 2023-11-03 13:24

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "23.11.2"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_commitnotification_decoration_type"),
    ]

    operations = [migrations.RunPython(update_version)]
