# Generated by Django 4.2.7 on 2023-12-27 17:00

from django.db import migrations, models
from shared.django_apps.migration_utils import RiskyAddField


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field bundle_analysis_commentid to pull
    --
    ALTER TABLE "pulls" ADD COLUMN "bundle_analysis_commentid" text NULL;
    COMMIT;
    """

    dependencies = [
        ("core", "0040_increment_version"),
    ]

    operations = [
        RiskyAddField(
            model_name="pull",
            name="bundle_analysis_commentid",
            field=models.TextField(null=True),
        ),
    ]
