# Generated by Django 4.2.7 on 2024-01-09 18:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field languages to repository
    --
    ALTER TABLE "repos" ADD COLUMN "languages" varchar[] DEFAULT '{}' NOT NULL;
    ALTER TABLE "repos" ALTER COLUMN "languages" DROP DEFAULT;
    COMMIT;
    """

    dependencies = [
        ("core", "0041_pull_bundle_analysis_commentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), blank=True, default=[], size=None
            ),
        ),
    ]
