# Generated by Django 4.2.7 on 2024-01-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field bundle_analysis_enabled to repository
    --
    ALTER TABLE "repos" ADD COLUMN "bundle_analysis_enabled" boolean DEFAULT false NULL;
    ALTER TABLE "repos" ALTER COLUMN "bundle_analysis_enabled" DROP DEFAULT;
    COMMIT;
    """

    dependencies = [
        ("core", "0042_repository_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="bundle_analysis_enabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
