# Generated by Django 4.2.7 on 2024-01-31 18:04

from django.db import migrations


def update_version(apps, schema):
    Constants = apps.get_model("core", "Constants")
    version = Constants.objects.get(key="version")
    version.value = "24.2.1"
    version.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_repository_coverage_enabled"),
    ]

    operations = [migrations.RunPython(update_version)]
