# Generated by Django 3.1.6 on 2021-08-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingupload",
            name="normalized_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profilingupload",
            name="normalized_location",
            field=models.TextField(null=True),
        ),
    ]
