# Generated by Django 3.1.13 on 2021-09-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiling", "0002_auto_20210817_2007"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilingcommit",
            name="commit_sha",
            field=models.TextField(null=True),
        ),
    ]
