# Generated by Django 3.1.6 on 2021-04-08 19:33

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.commit",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ReportSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("build_code", models.TextField(null=True)),
                ("build_url", models.TextField(null=True)),
                ("env", models.JSONField(null=True)),
                ("job_code", models.TextField(null=True)),
                ("name", models.CharField(max_length=100, null=True)),
                ("provider", models.CharField(max_length=50, null=True)),
                ("state", models.CharField(max_length=100)),
                ("storage_path", models.TextField()),
                ("order_number", models.IntegerField(null=True)),
                ("upload_type", models.CharField(max_length=100, default="uploaded")),
                ("upload_extras", models.JSONField(default=dict)),
            ],
            options={"db_table": "reports_upload",},
        ),
        migrations.CreateModel(
            name="SessionLevelTotals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branches", models.IntegerField()),
                ("coverage", models.DecimalField(decimal_places=2, max_digits=7)),
                ("hits", models.IntegerField()),
                ("lines", models.IntegerField()),
                ("methods", models.IntegerField()),
                ("misses", models.IntegerField()),
                ("partials", models.IntegerField()),
                ("files", models.IntegerField()),
                (
                    "report_session",
                    models.OneToOneField(
                        db_column="upload_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reportsession",
                    ),
                ),
            ],
            options={"db_table": "reports_uploadleveltotals",},
        ),
        migrations.CreateModel(
            name="RepositoryFlag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flag_name", models.CharField(max_length=255)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="core.repository",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ReportSessionFlagMembership",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.repositoryflag",
                    ),
                ),
                (
                    "report_session",
                    models.ForeignKey(
                        db_column="upload_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.reportsession",
                    ),
                ),
            ],
            options={"db_table": "reports_uploadflagmembership",},
        ),
        migrations.CreateModel(
            name="ReportSessionError",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_code", models.CharField(max_length=100)),
                ("error_params", models.JSONField(default=dict)),
                (
                    "report_session",
                    models.ForeignKey(
                        db_column="upload_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="reports.reportsession",
                    ),
                ),
            ],
            options={"db_table": "reports_uploaderror",},
        ),
        migrations.AddField(
            model_name="reportsession",
            name="flags",
            field=models.ManyToManyField(
                through="reports.ReportSessionFlagMembership",
                to="reports.RepositoryFlag",
            ),
        ),
        migrations.AddField(
            model_name="reportsession",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="reports.commitreport",
            ),
        ),
        migrations.CreateModel(
            name="ReportLevelTotals",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("branches", models.IntegerField()),
                ("coverage", models.DecimalField(decimal_places=2, max_digits=7)),
                ("hits", models.IntegerField()),
                ("lines", models.IntegerField()),
                ("methods", models.IntegerField()),
                ("misses", models.IntegerField()),
                ("partials", models.IntegerField()),
                ("files", models.IntegerField()),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.commitreport",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="ReportDetails",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "files_array",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), size=None
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.commitreport",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
