# Generated by Django 3.1.13 on 2021-11-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_auto_20211006_2211"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsession",
            name="state_id",
            field=models.IntegerField(
                choices=[(1, "uploaded"), (2, "processed"), (3, "error")], null=True
            ),
        ),
        migrations.AddField(
            model_name="reportsession",
            name="upload_type_id",
            field=models.IntegerField(
                choices=[(1, "uploaded"), (2, "carryforwarded")], null=True
            ),
        ),
    ]
