# Generated by Django 3.2.12 on 2022-09-22 11:57

from django.db import migrations, models

from utils.migrations import RiskyAddConstraint


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_auto_20211118_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitreport",
            name="code",
            field=models.CharField(default="default", max_length=100, null=True),
        ),
        RiskyAddConstraint(
            model_name="commitreport",
            constraint=models.UniqueConstraint(
                fields=("commit_id", "code"), name="unique_commit_id_code"
            ),
        ),
    ]
