# Generated by Django 3.2.12 on 2022-09-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_auto_20211118_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitreport",
            name="code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="commitreport",
            constraint=models.UniqueConstraint(
                fields=("commit_id", "code"), name="unique_commit_id_code"
            ),
        ),
    ]
