# Generated by Django 3.2.12 on 2022-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_auto_20211118_1150"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitreport",
            name="code",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
