# Generated by Django 3.2.12 on 2022-11-14 14:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_commitreport_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportResults",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.TextField(
                        choices=[("created", "Created"), ("ready", "Ready")], null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(null=True)),
                ("result", models.JSONField(default=dict)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.commitreport",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
