# Generated by Django 3.2.12 on 2022-11-02 08:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reports", "0004_commitreport_code"),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE UNIQUE INDEX CONCURRENTLY unique_commit_id_code_idx ON reports_commitreport ("commit_id", "code");'
        ),
    ]
