# Generated by Django 3.2.12 on 2022-12-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("reports", "0005_auto_20221114_1428"),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE UNIQUE INDEX CONCURRENTLY unique_commit_id_code_idx ON reports_commitreport ("commit_id", "code");'
        ),
    ]
