# Generated by Django 3.2.12 on 2023-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_auto_20230220_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryflag",
            name="deleted",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="reportsession",
            name="state_id",
            field=models.IntegerField(
                choices=[
                    (1, "UPLOADED"),
                    (2, "PROCESSED"),
                    (3, "ERROR"),
                    (4, "FULLY_OVERWRITTEN"),
                    (5, "PARTIALLY_OVERWRITTEN"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportsession",
            name="upload_type_id",
            field=models.IntegerField(
                choices=[(1, "UPLOADED"), (2, "CARRIEDFORWARD")], null=True
            ),
        ),
    ]
