# Generated by Django 3.2.12 on 2023-02-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_auto_20230220_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportresults",
            name="state",
            field=models.TextField(
                choices=[
                    ("created", "Created"),
                    ("ready", "Ready"),
                    ("pending", "Pending"),
                ],
                null=True,
            ),
        ),
    ]
