# Generated by Django 3.2.12 on 2023-02-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_auto_20230220_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportresults",
            name="state",
            field=models.TextField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                null=True,
            ),
        ),
    ]
