# Generated by Django 4.1.7 on 2023-05-29 14:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    # Generated SQL
    # BEGIN;
    # --
    # -- Alter field files_array on reportdetails
    # --
    # -- (no-op)
    # --
    # -- Rename field files_array on reportdetails to _files_array
    # --
    # -- (no-op)
    # --
    # -- Add field _files_array_storage_path to reportdetails
    # --
    # ALTER TABLE "reports_reportdetails" ADD COLUMN "files_array_storage_path" varchar(200) NULL;
    # --
    # -- Alter field _files_array on reportdetails
    # --
    # ALTER TABLE "reports_reportdetails" ALTER COLUMN "files_array" DROP NOT NULL;
    # COMMIT;

    dependencies = [
        ("reports", "0009_auto_20230223_1624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdetails",
            name="files_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), db_column="files_array", size=None
            ),
        ),
        migrations.RenameField(
            model_name="reportdetails",
            old_name="files_array",
            new_name="_files_array",
        ),
        migrations.AddField(
            model_name="reportdetails",
            name="_files_array_storage_path",
            field=models.URLField(db_column="files_array_storage_path", null=True),
        ),
        migrations.AlterField(
            model_name="reportdetails",
            name="_files_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(),
                db_column="files_array",
                null=True,
                size=None,
            ),
        ),
    ]
