# Generated by Django 4.2.7 on 2023-12-04 14:39

from django.db import migrations, models

from utils.migrations import RiskyAddIndex


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Add field report_type to commitreport
    --
    ALTER TABLE "reports_commitreport" ADD COLUMN "report_type" varchar(100) NULL;
    --
    -- Create index reports_com_commit__a03785_idx on field(s) commit_id, report_type, code of model commitreport
    --
    CREATE INDEX "reports_com_commit__a03785_idx" ON "reports_commitreport" ("commit_id", "report_type", "code");
    COMMIT;
    """

    dependencies = [
        ("reports", "0010_alter_reportdetails_files_array_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("coverage", "Coverage"),
                    ("test_results", "Test Results"),
                    ("bundle_analysis", "Bundle Analysis"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        RiskyAddIndex(
            model_name="commitreport",
            index=models.Index(
                fields=["commit_id", "report_type", "code"],
                name="reports_com_commit__a03785_idx",
            ),
        ),
    ]
