# Generated by Django 4.2.7 on 2023-12-04 16:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_pull_pulls_repoid_id"),
        ("reports", "0011_commitreport_report_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("testsuite", models.TextField()),
                (
                    "repository",
                    models.ForeignKey(
                        db_column="repoid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="core.repository",
                    ),
                ),
            ],
            options={
                "db_table": "reports_test",
            },
        ),
        migrations.CreateModel(
            name="TestInstance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration", models.FloatField()),
                ("outcome", models.IntegerField()),
                (
                    "report",
                    models.ForeignKey(
                        db_column="upload_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testruns",
                        to="reports.reportsession",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testruns",
                        to="reports.test",
                    ),
                ),
            ],
            options={
                "db_table": "reports_testrun",
            },
        ),
    ]
