# Generated by Django 4.2.7 on 2024-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_test_testinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="failure_message",
            field=models.TextField(null=True),
        ),
    ]
