# Generated by Django 4.2.7 on 2024-01-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0012_test_testinstance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testinstance",
            old_name="duration",
            new_name="duration_seconds",
        ),
    ]
