# Generated by Django 4.2.7 on 2024-01-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    BEGIN;
    --
    -- Rename field env on test to flags_hash
    --
    ALTER TABLE "reports_test" RENAME COLUMN "env" TO "flags_hash";
    --
    -- Alter field outcome on testinstance
    --
    ALTER TABLE "reports_testinstance" ALTER COLUMN "outcome" TYPE varchar(100) USING "outcome"::varchar(100);
    --
    -- Create constraint reports_test_repoid_name_testsuite_flags_hash on model test
    --
    ALTER TABLE "reports_test" ADD CONSTRAINT "reports_test_repoid_name_testsuite_flags_hash" UNIQUE ("repoid", "name", "testsuite", "flags_hash");
    COMMIT;
    """

    dependencies = [
        ("reports", "0013_test_testinstance"),
    ]

    operations = [
        migrations.RenameField(
            model_name="test",
            old_name="env",
            new_name="flags_hash",
        ),
        migrations.AlterField(
            model_name="testinstance",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("failure", "Failure"),
                    ("skip", "Skip"),
                    ("error", "Error"),
                    ("pass", "Pass"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="test",
            constraint=models.UniqueConstraint(
                fields=("repository", "name", "testsuite", "flags_hash"),
                name="reports_test_repoid_name_testsuite_flags_hash",
            ),
        ),
    ]
