# Generated by Django 4.2.7 on 2024-03-22 16:37

import uuid

import django.db.models.deletion
from django.db import migrations, models

"""
BEGIN;
--
-- Add field flake_symptom to testinstance
--
ALTER TABLE "reports_testinstance" ADD COLUMN "flake_symptom" varchar(100) NULL;
--
-- Create model Flake
--
CREATE TABLE "reports_flake" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "external_id" uuid NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "active" boolean NOT NULL, "test_id" text NOT NULL);
--
-- Add field flake_id to testinstance
--
ALTER TABLE "reports_testinstance" ADD COLUMN "flake_id" bigint NULL CONSTRAINT "reports_testinstance_flake_id_689137c1_fk_reports_flake_id" REFERENCES "reports_flake"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "reports_testinstance_flake_id_689137c1_fk_reports_flake_id" IMMEDIATE;
ALTER TABLE "reports_flake" ADD CONSTRAINT "reports_flake_test_id_03df5966_fk_reports_test_id" FOREIGN KEY ("test_id") REFERENCES "reports_test" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reports_flake_test_id_03df5966" ON "reports_flake" ("test_id");
CREATE INDEX "reports_flake_test_id_03df5966_like" ON "reports_flake" ("test_id" text_pattern_ops);
CREATE INDEX "reports_testinstance_flake_id_689137c1" ON "reports_testinstance" ("flake_id");
COMMIT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_testresultreporttotals"),
    ]

    operations = [
        migrations.AddField(
            model_name="testinstance",
            name="flake_symptom",
            field=models.CharField(
                choices=[
                    ("failed_in_default_branch", "Default Failure"),
                    ("consecutive_diff_outcomes", "Consecutive Diff Outcomes"),
                    ("unrelated_matching_failures", "Unrelated Matching Failures"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Flake",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField()),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flakes",
                        to="reports.test",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testinstance",
            name="flake_id",
            field=models.ForeignKey(
                db_column="flake_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testinstances",
                to="reports.flake",
            ),
        ),
    ]
