# Generated by Django 4.2.7 on 2024-04-02 14:56

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

"""
BEGIN;
--
-- Create model Flake
--
CREATE TABLE "reports_flake" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "external_id" uuid NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "active" boolean NOT NULL, "flake_symptoms" varchar(100)[] NULL, "test_id" text NOT NULL);
--
-- Add field flake to testinstance
--
ALTER TABLE "reports_testinstance" ADD COLUMN "flake_id" bigint NULL CONSTRAINT "reports_testinstance_flake_id_689137c1_fk_reports_flake_id" REFERENCES "reports_flake"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "reports_testinstance_flake_id_689137c1_fk_reports_flake_id" IMMEDIATE;
ALTER TABLE "reports_flake" ADD CONSTRAINT "reports_flake_test_id_03df5966_fk_reports_test_id" FOREIGN KEY ("test_id") REFERENCES "reports_test" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "reports_flake_test_id_03df5966" ON "reports_flake" ("test_id");
CREATE INDEX "reports_flake_test_id_03df5966_like" ON "reports_flake" ("test_id" text_pattern_ops);
CREATE INDEX "reports_testinstance_flake_id_689137c1" ON "reports_testinstance" ("flake_id");
COMMIT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0015_testresultreporttotals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flake",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField()),
                (
                    "flake_symptoms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        db_column="test_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flakes",
                        to="reports.test",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="testinstance",
            name="flake",
            field=models.ForeignKey(
                db_column="flake_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testinstances",
                to="reports.flake",
            ),
        ),
    ]
