# Generated by Django 3.2.12 on 2022-08-06 17:44

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0014_pull_pulls_author_updatestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelAnalysisRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_labels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "state_id",
                    models.IntegerField(
                        choices=[(1, "created"), (2, "finished"), (3, "error")]
                    ),
                ),
                ("result", models.JSONField(null=True)),
                (
                    "base_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_requests_as_base",
                        to="core.commit",
                    ),
                ),
                (
                    "head_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_requests_as_head",
                        to="core.commit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
