# Generated by Django 3.2.12 on 2023-01-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_version_v4_6_6"),
        ("labelanalysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelanalysisrequest",
            name="processing_params",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="labelanalysisrequest",
            name="base_commit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="label_requests_as_base",
                to="core.commit",
            ),
        ),
        migrations.AlterField(
            model_name="labelanalysisrequest",
            name="state_id",
            field=models.IntegerField(
                choices=[(1, "CREATED"), (2, "FINISHED"), (3, "ERROR")]
            ),
        ),
    ]
