# Generated by Django 3.2.12 on 2023-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labelanalysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="labelanalysisrequest",
            name="processing_params",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="labelanalysisrequest",
            name="state_id",
            field=models.IntegerField(
                choices=[(1, "CREATED"), (2, "FINISHED"), (3, "ERROR")]
            ),
        ),
    ]
