# Generated by Django 3.1.6 on 2021-04-29 12:03

from django.db import migrations, models

import sys

is_testing = "pytest" in sys.modules


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = (
        [
            migrations.CreateModel(
                name="EnvVarsExposed",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("owner_id", models.IntegerField(blank=True, null=True)),
                    ("repo_id", models.IntegerField(blank=True, null=True)),
                    ("is_repo_private", models.BooleanField(blank=True, null=True)),
                    (
                        "severity_from_log_analysis",
                        models.CharField(blank=True, max_length=50, null=True),
                    ),
                    ("exists_on_codecov", models.BooleanField(blank=True, null=True)),
                    (
                        "known_clone_by_attacker",
                        models.BooleanField(blank=True, null=True),
                    ),
                    ("exposed_env_vars", models.TextField(blank=True, null=True)),
                    (
                        "sensitive_exposed_in_git_origin",
                        models.TextField(blank=True, null=True),
                    ),
                ],
                options={
                    "db_table": "env_vars_exposed",
                    "unique_together": {("owner_id", "repo_id")},
                },
            ),
        ]
        if is_testing
        else []
    )
