# Generated by Django 3.1.6 on 2021-07-05 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_pull_user_provided_base_sha"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitComparison",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("pending", "Pending"),
                            ("error", "Error"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                    ),
                ),
                ("report_storage_path", models.CharField(max_length=150, null=True)),
                (
                    "base_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_commit_comparisons",
                        to="core.commit",
                    ),
                ),
                (
                    "compare_commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compare_commit_comparisons",
                        to="core.commit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
