# Generated by Django 3.1.6 on 2021-09-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitcomparison",
            name="patch_totals",
            field=models.JSONField(null=True),
        ),
    ]
