# Generated by Django 3.2.12 on 2022-07-01 00:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_auto_20211118_1150"),
        ("compare", "0003_commitcomparison_error"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlagComparison",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coverage_totals", models.JSONField(null=True)),
                ("patch_totals", models.JSONField(null=True)),
                (
                    "commit_comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commit_comparisons",
                        to="compare.commitcomparison",
                    ),
                ),
                (
                    "repositoryflag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flag_comparisons",
                        to="reports.repositoryflag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
