# Generated by Django 3.2.12 on 2022-07-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compare", "0004_flagcomparison"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flagcomparison",
            old_name="coverage_totals",
            new_name="head_totals",
        ),
        migrations.AddField(
            model_name="flagcomparison",
            name="base_totals",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="flagcomparison",
            name="commit_comparison",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flag_comparisons",
                to="compare.commitcomparison",
            ),
        ),
    ]
