# Generated by Django 4.1.7 on 2023-04-20 14:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compare", "0005_auto_20220713_2210"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentComparison",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("component_id", models.TextField()),
                ("head_totals", models.JSONField(null=True)),
                ("base_totals", models.JSONField(null=True)),
                ("patch_totals", models.JSONField(null=True)),
                (
                    "commit_comparison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_comparisons",
                        to="compare.commitcomparison",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="componentcomparison",
            index=models.Index(
                fields=["commit_comparison_id", "component_id"],
                name="component_comparison_component",
            ),
        ),
    ]
