def run_sql(schema_editor):
    schema_editor.execute(
        """
        CREATE TABLE IF NOT EXISTS "users" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "external_id" uuid NOT NULL UNIQUE,
            "created_at" timestamp with time zone NOT NULL,
            "updated_at" timestamp with time zone NOT NULL,
            "email" citext NULL,
            "name" text NULL,
            "is_staff" boolean NULL,
            "is_superuser" boolean NULL
        );
    """
    )
