# Generated by Django 3.2.12 on 2022-08-06 17:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0014_pull_pulls_author_updatestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticAnalysisSingleFileSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_hash", models.UUIDField()),
                ("content_location", models.TextField()),
                (
                    "state_id",
                    models.IntegerField(
                        choices=[(1, "created"), (2, "valid"), (3, "rejected")]
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.repository",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticAnalysisSuite",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.commit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaticAnalysisSuiteFilepath",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filepath", models.TextField()),
                (
                    "analysis_suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filepaths",
                        to="staticanalysis.staticanalysissuite",
                    ),
                ),
                (
                    "file_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filepaths",
                        to="staticanalysis.staticanalysissinglefilesnapshot",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="staticanalysissuite",
            constraint=models.UniqueConstraint(
                fields=("external_id",), name="staticanalysis_external_id_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="staticanalysissinglefilesnapshot",
            constraint=models.UniqueConstraint(
                fields=("repository", "file_hash"), name="staticanalysis_repo_filehash"
            ),
        ),
    ]
