# Generated by Django 3.2.12 on 2022-04-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("legacy_migrations", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        create table if not exists yaml_history
                        (
                            id serial primary key,
                            ownerid   integer                  not null
                                references owners
                                    on delete cascade,
                            timestamp timestamp with time zone not null,
                            author    integer
                                references owners
                                    on delete cascade,
                            message   text,
                            source    text                     not null,
                            diff      text
                        );
                    """,
                    reverse_sql="drop table yaml_history;",
                ),
                migrations.RunSQL(
                    sql="""
                        create index if not exists yaml_history_ownerid_timestamp
                        on yaml_history (ownerid, timestamp); 
                    """,
                    reverse_sql="drop index if exists yaml_history_ownerid_timestamp;",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="YamlHistory",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("timestamp", models.DateTimeField()),
                        ("message", models.TextField(blank=True, null=True)),
                        ("source", models.TextField()),
                        ("diff", models.TextField(null=True)),
                        (
                            "author",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="authors",
                                db_column="author",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "ownerid",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="ownerids",
                                db_column="ownerid",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "yaml_history",
                    },
                ),
                migrations.AddIndex(
                    model_name="yamlhistory",
                    index=models.Index(
                        fields=["ownerid", "timestamp"],
                        name="yaml_histor_ownerid_74e79b_idx",
                    ),
                ),
            ],
        )
    ]
