# Generated by Django 3.2.12 on 2023-01-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legacy_migrations", "0002_yaml_history_table"),
    ]

    # These 2 triggers were wrong in the database and did not match what is found
    # in the codebase.  They were casting the values to ::text types which was breaking
    # the case-insensitive comparisons of ::citext.  These migrations just drop and
    # recreate the triggers exactly as they appear in the `legacy_sql` files.

    operations = [
        migrations.RunSQL(
            """
        drop trigger owners_before_update on owners;

        create trigger owners_before_update before update on owners
        for each row
        when (new.username is not null and new.username is distinct from old.username)
        execute procedure owners_before_insert_or_update();
        """
        ),
        migrations.RunSQL(
            """
        drop trigger repos_before_update on repos;
        
        create trigger repos_before_update before update on repos
        for each row
        when (new.name is not null and new.name is distinct from old.name)
        execute procedure repos_before_insert_or_update();
        """
        ),
    ]
