# Created on 2025-03-20 14:30:18
name: Upload Overwatch - 2025-03-20 14:30:18

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches-ignore:
      - main

jobs:
  upload-overwatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install UV
        run: pip install uv
      - name: Install Project Dependencies
        run: |
          uv export --format requirements-txt > requirements.txt
          uv pip install -r requirements.txt --system
      - name: Install Static Analysis Tools
        run: |
          pip install mypy==1.15.0
          pip install ruff==0.9.6
      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          # Install libssl1.1 from Ubuntu 20.04 repositories
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      - name: Install Overwatch CLI
        run: |
          curl -o overwatch-cli https://overwatch.codecov.dev/linux/cli
          chmod +x overwatch-cli
      - name: Run Overwatch CLI
        run: |
          ./overwatch-cli \
            --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} \
            --organization-slug codecov \
            --pullid 1183 \
            python \
            --python-path $(which python3)
